DeaconCCGManagement/Controllers/ClaimsController.cs
using System;
using System.Collections.Generic;
using System.Security.Claims;
using System.Security.Principal;
using System.Web.Mvc;
using DeaconCCGManagement.Helpers;

namespace DeaconCCGManagement.Controllers
{
    public class ClaimsController : ControllerBase
    {
        [Authorize]
        public ViewResult Index()
        {
            var identity = User.Identity as ClaimsIdentity;
            return View(identity.Claims);
        }



        public ActionResult TestAddClaims()
        {
            var identity = User.Identity as ClaimsIdentity;

            var claims = new List<Claim>
            {
                new Claim(ClaimTypes.Role, "Pastor"),
                new Claim(ClaimTypes.Role, "Administrator"),
                new Claim(ClaimTypes.Role, "Deacon Leadership"),
                new Claim(ClaimTypes.Role, "Deacon"),
                new Claim(ClaimTypes.Role, "TestRole"),
            };
            Request.LogonUserIdentity.AddClaims(claims);

            //identity.AddClaims(claims);

            var userSurname = AuthHelper.GetUserSurname(User.Identity.Name);
            var claim = new Claim(ClaimTypes.Surname, userSurname);

            if (!identity.HasClaim(c => c.Type == ClaimTypes.Surname))
            {
                Request.LogonUserIdentity.AddClaim(claim);
                //identity.AddClaim(claim);
            }

            return RedirectToAction("Index");
        }
    }
}

DeaconCCGManagement/Views/Claims/Index.cshtml
@model IEnumerable<System.Security.Claims.Claim>

  <!--Identity Claims Test Link-->
@*<div class="container">
    <div class="row">
        <div class="col-lg-12">
            <p style="font-size: 3em">
                @Html.ActionLink("Test: Add Claims", "TestAddClaims", "Claims")
            </p>

        </div>
    </div>
</div>*@

@Html.Partial("_Breadcrumbs", "Claims")

<div class="bg-primary panel-body"><h4>Claims</h4></div>
<table class="table table-condensed table-bordered">
    <tr>
        <th>Subject</th>
        <th>Issuer</th>
        <th>Type</th>
        <th>Value</th>
    </tr>
    @if (Model == null || Model.Count() == 0)
    {
        <tr><td colspan="4" class="text-center">No Claims</td></tr>
    }
    else
    {
        foreach (var claim in Model.OrderBy(x => x.Type))
        {
            <tr>
                <td>@claim.Subject.Name</td>
                <td>@claim.Issuer</td>
                <td identity-claim-type="@claim.Type"></td>
                <td>@claim.Value</td>
            </tr>
        }
    }
</table>