DeaconCCGManagement/ViewModels/BulkContactViewModel.cs
using System.Collections.Generic;
using System.Web.Mvc;

namespace DeaconCCGManagement.ViewModels
{
    public class BulkContactViewModel
    {
        public IList<BulkContactMember> Members { get; set; }

        public CreateContactRecordViewModel CreateContactVM { get; set; }

        public int? ContactTypeId { get; set; }

        public SelectList ContactTypes { get; set; }

        public bool NoMembersSelected { get; set; }
    }

    public class BulkContactMember
    {
        public int MemberId { get; set; }

        public string MemberFullName { get; set; }
    }
}

DeaconCCGManagement/Controllers/BulkContactController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using DeaconCCGManagement.Models;
using DeaconCCGManagement.ViewModels;
using DeaconCCGManagement.Services;
using System.Web.Routing;

namespace DeaconCCGManagement.Controllers
{
    [Authorize]
    public class BulkContactController : ControllerBase
    {
        private readonly BulkContactService _service;
        private readonly CcgMembersService _membersService;

        public BulkContactController()
        {
            _service = new BulkContactService(base.unitOfWork);
            _membersService = new CcgMembersService(base.unitOfWork);
        }

        // GET: BulkContact
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ContactSelected(int? ccgId, bool getAll, string query, 
            bool allAccess, bool selectAll = false, params int?[] memberIds)
        {

            IEnumerable<CCGMember> members = new List<CCGMember>();
            string userEmail = User.Identity.Name;

            #region Get selected members
            if (selectAll)
            {
                ActionResult actionResult;
                members = _membersService.GetMembersList(ccgId,
                    getAll, query, allAccess, userEmail, out actionResult);

                // User may not get authorized and redirected
                if (actionResult != null) return actionResult;
            }
            else // multi-selected members but not all
            {
                // Get members from data store where id's match those in view model.
                if (memberIds != null && memberIds.Length != 0)
                {
                    members = _membersService.GetSelecteMembers(memberIds);
                }
            }
            #endregion

            // Map list of domain models back to list of view models.
            var selectedMembersVM = Mapper.Map<IList<ListMembersViewModel>>(members);

            // For dropdown list
            var contactTypes = unitOfWork.ContactTypeRepository.GetContactTypesSorted();

            // Deafult selected contact type: 'District Newsletter'
            var defaultSelected = contactTypes
                .SingleOrDefault(ct => ct.Name.Equals("District Newsletter", StringComparison.CurrentCultureIgnoreCase)
                                 || ct.Name.Contains("Newsletter"));

            var bulkContactMembers = new List<BulkContactMember>();

            _service.AddToBulkContactMembers(selectedMembersVM, bulkContactMembers);

            #region Create view model
            var bulkContactViewModel = new BulkContactViewModel
            {
                Members = bulkContactMembers,
                ContactTypes = new SelectList(contactTypes, "Id", "Name", defaultSelected?.Id),
                CreateContactVM = new CreateContactRecordViewModel { ContactDate = DateTime.Now },
                NoMembersSelected = selectedMembersVM.Count == 0
            };
            #endregion

            return View("ContactSelected", bulkContactViewModel);
        }
      

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(BulkContactViewModel viewModel)
        {
            var user = unitOfWork.AppUserRepository.FindUserByEmail(User.Identity.Name);
            if (viewModel.ContactTypeId == null)
            {
                // temporary; use district newsletter as default
                viewModel.ContactTypeId = 4;
            }
            
            foreach (var member in viewModel.Members)
            {
                //var member = db.MemberRepository.FindMemberById()
                var contact = new ContactRecord
                {
                    AppUserId = user.Id,
                    Archive = false,
                    CCGMemberId = member.MemberId,
                    Comments = viewModel.CreateContactVM.Comments,
                    ContactDate = viewModel.CreateContactVM.ContactDate,
                    ContactTypeId = (int) viewModel.ContactTypeId,
                    Subject = viewModel.CreateContactVM.Subject,
                    Timestamp = DateTime.Now
                };

                StoreContact(contact);
            }
            ViewBag.Complete = true;
            var contactTypes = unitOfWork.ContactTypeRepository.GetContactTypesSorted();
            var defaultSelected = contactTypes
                .SingleOrDefault(ct => ct.Name.Equals("District Newsletter", StringComparison.CurrentCultureIgnoreCase)
                                 || ct.Name.Contains("Newsletter"));

            viewModel.ContactTypes = new SelectList(contactTypes, "Id", "Name", defaultSelected?.Id);

            return View("ContactSelected", viewModel);
        }

        private void StoreContact(ContactRecord contactRecord)
        {
            unitOfWork.ContactRecordRepository.Add(contactRecord);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BulkEmail(BulkContactViewModel viewModel)
        {
            if (viewModel.Members.Count == 0)
                return RedirectToAction("ContactSelected");

            var user = unitOfWork.AppUserRepository.FindUserByEmail(User.Identity.Name);

            var emailContact = new EmailContact
            {
                FromEmailAddress = user.Email,
                ToEmailAddress = "temp@ccg.com",
                SenderName = user.FullName,
                DateSent = DateTime.Now,
            };

            var emailViewModel = new EmailViewModel
            {
                EmailContact = emailContact,
                Bulk = true,
                Members = viewModel.Members
            };

            TempData["EmailViewModel"] = emailViewModel;
            return RedirectToAction("SendBulkEmail", "Email");
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult BulkTextMessage(BulkContactViewModel viewModel)
        {
            if (viewModel.Members.Count == 0)            
                return RedirectToAction("ContactSelected");            

            var user = unitOfWork.AppUserRepository.FindUserByEmail(User.Identity.Name);

            var textMessageContact = new TextMessageContact
            {
                ToPhoneNumber = string.Empty,
                FromPhoneNumber = user.PhoneNumber,
                DateSent = DateTime.Now
            };

            var textMessageViewModel = new TextMessageViewModel
            {
                TextMessageContact = textMessageContact,
                Bulk = true,
                Members = viewModel.Members
            };

            TempData["TextMessageViewModel"] = textMessageViewModel;

            RouteValueDictionary routeDictionary = new RouteValueDictionary();
            routeDictionary.Add("TextMessageViewModel", textMessageViewModel);

            return RedirectToAction("SendBulkTextMessage", "Sms", routeDictionary);
        }
    }
}

DeaconCCGManagement/Views/BulkContact/BulkContactTest.cshtml
@{
    ViewBag.Title = "BulkContactTest";
}

<h2>Bulk Contact Test</h2>

DeaconCCGManagement/Views/BulkContact/ContactSelected.cshtml
@using DeaconCCGManagement.Helpers
@using DeaconCCGManagement.Models
@using DeaconCCGManagement.ViewModels
@model BulkContactViewModel

@{
    ViewBag.Title = "Contact Selected Members";

    if (ViewBag.Complete == null)
    {
        ViewBag.Complete = false;
    }
   
}

@section styles{
   @Styles.Render("~/Content/bootstrap-datetimepicker.min.css")
}

@Html.Partial("_Breadcrumbs", "Bulk Contact")


@if (ViewBag.Complete)
{
    <h2 class="alert alert-success">
        Your contact record has been saved
        for all the selected members.</h2>
}
else
{
    <h2>Bulk Contact</h2>
}





@if (@Model.NoMembersSelected)
{
    <h3>No Members Selected</h3>
     @Html.Partial("_BackToListLink")
    <br/>
}


<div id="bulk-contact-options">
    <p>
        <button class="btn btn-primary" type="button" data-toggle="collapse"
                data-target="#listMembers" id="btnShowHideMembers">
            <span id="btnIcon" class="glyphicon glyphicon-eye-open"></span>
            <span id="spanShowHideMembers">Show Selected Members</span>
        </button>
    </p>
    <div class="collapse" id="listMembers">
        <div class="well">
            <p>
                @{
                    if (Model?.Members != null)
                    {
                        int num = 1;
                        foreach (var item in Model.Members)
                        {
                            <label>@num. @item.MemberFullName</label>
                            <br />
                            num++;
                        }
                    }

                }
            </p>
        </div>
    </div>

    <br />

    <div class="well">
        <h4>Send A Bulk Email or Text Message</h4>

        @using (Html.BeginForm("BulkEmail", "BulkContact", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @*Creates hidden field for each member's id*@
        for (int i = 0; i < Model.Members?.Count; i++)
        {
            @Html.HiddenFor(modelItem => modelItem.Members[i].MemberId)
            @Html.HiddenFor(modelItem => modelItem.Members[i].MemberFullName)
        }

        <p>
            <button class="btn btn-primary" type="submit">
                <span class="fa fa-envelope-o"></span> Bulk Email
            </button>
        </p>
        }

        @using (Html.BeginForm("BulkTextMessage", "BulkContact", FormMethod.Post))
        {
            @Html.AntiForgeryToken()

            @*Creates hidden field for each member's id*@
        for (int i = 0; i < Model.Members?.Count; i++)
        {
            @Html.HiddenFor(modelItem => modelItem.Members[i].MemberId)
            @Html.HiddenFor(modelItem => modelItem.Members[i].MemberFullName)
        }

        <p>
            <button class="btn btn-primary" type="submit">
                <span class="glyphicon glyphicon-phone"></span> Bulk Text Message
            </button>
        </p>
        }
    </div>

    <P>
        <span style="font-size: 2.0em; font-weight: bold">or</span>
    </P>

    @using (Html.BeginForm("Create", "BulkContact", FormMethod.Post))
    {
        @Html.AntiForgeryToken()

     @*Creates hidden field for each member's id*@
    for (int i = 0; i < Model?.Members?.Count; i++)
    {
        @Html.HiddenFor(modelItem => modelItem.Members[i].MemberId)
        @Html.HiddenFor(modelItem => modelItem.Members[i].MemberFullName)
    }

    <div class="well well-md">
        <div class="form-horizontal">
            <h4>New Contact Record for <em>All</em> Selected Members</h4>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.CreateContactVM.ContactDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-3" style="padding: 0 0 0 15px">
                    <div class="input-group date datepicker">
                        @Html.EditorFor(model => model.CreateContactVM.ContactDate, new { htmlAttributes = new { @class = "form-control dateMask" } })
                        <span class="input-group-addon addOn">
                            <button class="btn btn-default calendar" type="button">
                                <span class="fa fa-calendar"></span>
                            </button>
                        </span>
                    </div>
                    @Html.ValidationMessageFor(model => model.CreateContactVM.ContactDate, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreateContactVM.Subject, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreateContactVM.Subject, new { htmlAttributes = new { @class = "form-control", id = "subject" } })
                    @Html.ValidationMessageFor(model => model.CreateContactVM.Subject, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreateContactVM.Comments, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.CreateContactVM.Comments, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.CreateContactVM.Comments, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CreateContactVM.ContactTypes, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @if (Model.ContactTypes != null)
                    {
                        @Html.DropDownListFor(model => model.ContactTypeId, Model.ContactTypes, new { @class = "form-control" })
                        @Html.ValidationMessageFor(model => model.CreateContactVM.ContactTypes, "", new { @class = "text-danger" })
                    }
                    
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
    }
</div>



@section Scripts{

    @Scripts.Render("~/Scripts/moment.min.js")
    @Scripts.Render("~/Scripts/bootstrap-datetimepicker.min.js")
    @Scripts.Render("~/Scripts/App/DatePicker.js")
    @Scripts.Render("~/Scripts/jquery.maskedinput.js")
    @Scripts.Render("~/Scripts/App/DateMask.js")
    @Scripts.Render("~/Scripts/App/GetBackToListUrl.js")

    <script type="text/javascript">
        $(function () {
            $("#subject").focus();
        });
    </script>

    <script type="text/javascript">
        $(function () {

            var noMembersSelected = "@Model.NoMembersSelected";

            // Hide bulk contact options if no members selected
            if (noMembersSelected === "True") {
                $("#bulk-contact-options").hide();
            }

            // When the collapsible element is shown,
            // change the button's text to 'Hide Selected Members'
            $('#listMembers').on('show.bs.collapse', function () {
                $('#spanShowHideMembers').text('Hide Selected Members');

                // Toggle icon
                $('#btnIcon').removeClass('glyphicon glyphicon-eye-open');
                $('#btnIcon').addClass('glyphicon glyphicon-eye-close');
            });
            // When the collapsible element is collpased,
            // change the button's text to 'Show Selected Members'
            $('#listMembers').on('hide.bs.collapse', function () {
                $('#spanShowHideMembers').text('Show Selected Members');

                // Toggle icon
                $('#btnIcon').removeClass('glyphicon glyphicon-eye-close');
                $('#btnIcon').addClass('glyphicon glyphicon-eye-open');
            });
        });
    </script>
}

DeaconCCGManagement/Views/BulkContact/Index.cshtml
@{
    ViewBag.Title = "Index";
}

@Html.Partial("_Breadcrumbs", "Bulk Contact")

<h2>Index</h2>

DeaconCCGManagement/Views/BulkContact/Send.cshtml
@using DeaconCCGManagement.Helpers
@using DeaconCCGManagement.Models
@using DeaconCCGManagement.ViewModels
@model IList<ListMembersViewModel>

@{
    ViewBag.Title = "Send";
}

@Html.Partial("_Breadcrumbs", "Send Bulk Contact")


<h2>Send</h2>



<h2>Selected Members</h2>

@if (Model.Count == 0)
{
    <h3>No Members Selected</h3>
}

@{
    int num = 1;
    foreach (var item in Model)
    {
        <label>@num. @item.FullName </label> <br />
        num++;
    }
}