DeaconCCGManagement/ViewModels/DownloadAsPdf.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace DeaconCCGManagement.ViewModels
{
    public class DownloadAsPdf
    {
    }
}

DeaconCCGManagement/ViewModels/FilterRecordsGroup.cs
using System.Web.Mvc;
using DeaconCCGManagement.enums;

namespace DeaconCCGManagement.ViewModels
{
    public class FilterRecordsGroup
    {
        public DateRangeFilter DateRangeFilter { get; set; }
        public SelectList CCGs { get; set; }
        public bool FilterCCGs { get; set; }

    }
}

DeaconCCGManagement/Controllers/PDFController.cs
using System;
using System.Linq;
using System.Web.Mvc;
using Rotativa.Core;
using Rotativa.MVC;

namespace DeaconCCGManagement.Controllers
{
    public class PDFController : ControllerBase
    {
        public ActionResult DownloadUrlAsPdf(string url, string fileName)
        {
            fileName = GetFileNameWithDate(fileName);
            fileName = AddExt(fileName);

            // Get cookies from the request and pass them to Rotativa.
            // Necessary to make PDFs from action methods with Authorization attribute
            var cookies = Request.Cookies.AllKeys
                  .ToDictionary(key => key, key => Request.Cookies[key]?.Value);
            
            var options = new DriverOptions
            {
                Cookies = cookies
            };
          
            return new UrlAsPdf(url) { FileName = fileName, RotativaOptions = options };
        }

        public ActionResult DownloadChangeRequestAsPdf(int? id)
        {
            var changeRequest = unitOfWork.ChangeRequestRepository.FindById(id);
            var fileName = GetFileNameWithDate("Change-Request");
            fileName = $"{fileName}-{changeRequest.CcgMember.FirstName}-{changeRequest.CcgMember.LastName}";
            fileName = AddExt(fileName);
            return new ActionAsPdf("../ChangeRequests/ChangeRequest", new { id = id }) { FileName = fileName };
        }

        private string GetFileNameWithDate(string fileName)
        {
            return $"{fileName}-{DateTime.Now.Year}-{DateTime.Now.Month}-{DateTime.Now.Day}";
        }

        private string AddExt(string fileName)
        {
            return $"{fileName}.pdf";
        }
    }
}

DeaconCCGManagement/Views/Shared/_BackToListLink.cshtml
<div>
    <p id="backToListUrl">
        <a id="backToListLink" href="">Back to List</a>
    </p>
</div>

DeaconCCGManagement/Views/Shared/_BootstrapModalDialog.cshtml
<!-- Button trigger modal -->
<button class="btn btn-primary btn-lg" data-toggle="modal" data-target="#myModal">
    Click for modal dialog fun
</button>


<!-- Modal dialog -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog"
     aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal"
                        aria-hidden="true">
                    &times;
                </button>
                <h4 class="modal-title" id="myModalLabel">
                    @ViewBag.Message
                    This is the modal dialog!
                </h4>
            </div>
            <div class="modal-body">
                Quite exciting, isn't it?
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default"
                        data-dismiss="modal">
                    Close
                </button>
                <button type="button" class="btn btn-primary">
                    Acknowledge how exciting this is
                </button>
            </div>
        </div>
    </div>
</div>

DeaconCCGManagement/Views/Shared/_Breadcrumbs.cshtml
@model string
    
<!--Breadcrumbs-->
<div id="breadcrumb_link_text" hidden="hidden">@Model</div>

@if (!@Model.Equals("Home"))
{   
     <ol id="breadcrumbs" class="breadcrumb"></ol> 
}
<!-- / Breadcrumbs-->

DeaconCCGManagement/Views/Shared/_ConsoleLayout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>SB Admin - Start Bootstrap Template</title>

    @*@Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")*@


    <link href="~/Console/bootstrap.min.css" rel="stylesheet" />

    <link href="~/Console/font-awesome.min.css" rel="stylesheet" />

    <link href="~/Console/sb-admin.css" rel="stylesheet" />




    @RenderSection("styles", required: false)

    
  
</head>

<body class="fixed-nav sticky-footer bg-dark" id="page-top">
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top" id="mainNav">
        <a class="navbar-brand" href="index.html">Start Bootstrap</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav navbar-sidenav" id="exampleAccordion">
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Dashboard">
                    <a class="nav-link" href="index.html">
                        <i class="fa fa-fw fa-dashboard"></i>
                        <span class="nav-link-text">Dashboard</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Charts">
                    <a class="nav-link" href="charts.html">
                        <i class="fa fa-fw fa-area-chart"></i>
                        <span class="nav-link-text">Charts</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Tables">
                    <a class="nav-link" href="tables.html">
                        <i class="fa fa-fw fa-table"></i>
                        <span class="nav-link-text">Tables</span>
                    </a>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Components">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseComponents" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-wrench"></i>
                        <span class="nav-link-text">Components</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseComponents">
                        <li>
                            <a href="navbar.html">Navbar</a>
                        </li>
                        <li>
                            <a href="cards.html">Cards</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Example Pages">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseExamplePages" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-file"></i>
                        <span class="nav-link-text">Example Pages</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseExamplePages">
                        <li>
                            <a href="login.html">Login Page</a>
                        </li>
                        <li>
                            <a href="register.html">Registration Page</a>
                        </li>
                        <li>
                            <a href="forgot-password.html">Forgot Password Page</a>
                        </li>
                        <li>
                            <a href="blank.html">Blank Page</a>
                        </li>
                    </ul>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Menu Levels">
                    <a class="nav-link nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti" data-parent="#exampleAccordion">
                        <i class="fa fa-fw fa-sitemap"></i>
                        <span class="nav-link-text">Menu Levels</span>
                    </a>
                    <ul class="sidenav-second-level collapse" id="collapseMulti">
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a href="#">Second Level Item</a>
                        </li>
                        <li>
                            <a class="nav-link-collapse collapsed" data-toggle="collapse" href="#collapseMulti2">Third Level</a>
                            <ul class="sidenav-third-level collapse" id="collapseMulti2">
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                                <li>
                                    <a href="#">Third Level Item</a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </li>
                <li class="nav-item" data-toggle="tooltip" data-placement="right" title="Link">
                    <a class="nav-link" href="#">
                        <i class="fa fa-fw fa-link"></i>
                        <span class="nav-link-text">Link</span>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav sidenav-toggler">
                <li class="nav-item">
                    <a class="nav-link text-center" id="sidenavToggler">
                        <i class="fa fa-fw fa-angle-left"></i>
                    </a>
                </li>
            </ul>
            <ul class="navbar-nav ml-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" id="messagesDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-envelope"></i>
                        <span class="d-lg-none">
                            Messages
                            <span class="badge badge-pill badge-primary">12 New</span>
                        </span>
                        <span class="indicator text-primary d-none d-lg-block">
                            <i class="fa fa-fw fa-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="messagesDropdown">
                        <h6 class="dropdown-header">New Messages:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>David Miller</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">Hey there! This new version of SB Admin is pretty awesome! These messages clip off when they reach the end of the box so they don't overflow over to the sides!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>Jane Smith</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I was wondering if you could meet for an appointment at 3:00 instead of 4:00. Thanks!</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <strong>John Doe</strong>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">I've sent the final files over to you for review. When you're able to sign off of them let me know and we can discuss distribution.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="#">View all messages</a>
                    </div>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle mr-lg-2" id="alertsDropdown" href="#" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        <i class="fa fa-fw fa-bell"></i>
                        <span class="d-lg-none">
                            Alerts
                            <span class="badge badge-pill badge-warning">6 New</span>
                        </span>
                        <span class="indicator text-warning d-none d-lg-block">
                            <i class="fa fa-fw fa-circle"></i>
                        </span>
                    </a>
                    <div class="dropdown-menu" aria-labelledby="alertsDropdown">
                        <h6 class="dropdown-header">New Alerts:</h6>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-danger">
                                <strong>
                                    <i class="fa fa-long-arrow-down fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">
                            <span class="text-success">
                                <strong>
                                    <i class="fa fa-long-arrow-up fa-fw"></i>Status Update
                                </strong>
                            </span>
                            <span class="small float-right text-muted">11:21 AM</span>
                            <div class="dropdown-message small">This is an automated server response message. All systems are online.</div>
                        </a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item small" href="#">View all alerts</a>
                    </div>
                </li>
                <li class="nav-item">
                    <form class="form-inline my-2 my-lg-0 mr-lg-2">
                        <div class="input-group">
                            <input class="form-control" type="text" placeholder="Search for...">
                            <span class="input-group-btn">
                                <button class="btn btn-primary" type="button">
                                    <i class="fa fa-search"></i>
                                </button>
                            </span>
                        </div>
                    </form>
                </li>
                <li class="nav-item">
                    <a class="nav-link" data-toggle="modal" data-target="#exampleModal">
                        <i class="fa fa-fw fa-sign-out"></i>Logout
                    </a>
                </li>
            </ul>
        </div>
    </nav>
    <!-- / Navigation-->
    <div class="content-wrapper">
        <div class="container-fluid">

            @RenderBody()

        </div><!-- /.container-fluid-->
    </div><!-- /.content-wrapper-->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fa fa-angle-up"></i>
    </a>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/Scripts/App/BreadcrumbTrail.js")



    <script src="~/Console/popper.min.js"></script>
    <script src="~/Console/jquery.easing.min.js"></script>
    <script src="~/Console/sb-admin.js"></script>

    @RenderSection("scripts", required: false)


</body>

</html>

DeaconCCGManagement/Views/Shared/_CreateButton.cshtml
@using DeaconCCGManagement.ViewModels
@model CreateButtonViewModel

@{
    // If null use the deafult action name "Create"
    string actionName = string.IsNullOrEmpty(Model.ActionName) ? "Create" : Model.ActionName;
}

@using (@Html.BeginForm(actionName, Model.ControllerName, FormMethod.Get))
{

    if (Model.MemberId != null)
    {
        @Html.Hidden("id", Model.MemberId)
    }

    <button class="btn btn-success" type="submit">
        Create <span class="fa fa-plus-circle"></span>
    </button>
}

DeaconCCGManagement/Views/Shared/_DownloadAsPdf.cshtml
@model string
@{
    string fileName = Model;
    string url = Request?.Url?.PathAndQuery;
}

<!--download as pdf-->
@using (Html.BeginForm("DownloadUrlAsPdf", "PDF", FormMethod.Get))
{
    @Html.Hidden("url", url);
    @Html.Hidden("fileName", fileName);

    <div class="form-group">
        <div class="col-md-12">
            <button type="submit" class="btn btn-primary">
                Download As PDF <i class="fa fa-download"></i>
            </button>
        </div>
    </div>
}<!-- / download as pdf-->

DeaconCCGManagement/Views/Shared/_ItemsPerPage.cshtml
@using DeaconCCGManagement.Helpers
@using DeaconCCGManagement.ViewModels
@model ItemsPerPageSelect

@{
    Model.ItemsPerPage = new[] { 5, 10, 25, 50, 100 }; ;
}

<!--Items per page-->
<div class="btn-group dropup">

    @Html.Partial("_ItemsPerPageButton", "Items Per Page")

    <ul class="dropdown-menu">
        @foreach (var numItems in Model.ItemsPerPage)
        {
            <li>
                <a href="@ViewHelper.GetUrlWithPerPageQuery(numItems, Model.AbsPath, Model.QueryStrings)">@numItems</a>
            </li>
        }

        @if (Model.ListAllOption) 
        {

            <li role="separator" class="divider"></li>
            <li>
                <a href="@ViewHelper.GetUrlWithPerPageQuery(Model.AbsPath, Model.QueryStrings, "listAll")">@Model.ListAllText</a>
            </li>
        }
    </ul>
</div> <!-- / Items per page-->

DeaconCCGManagement/Views/Shared/_ItemsPerPageButton.cshtml
@model string

<button type="button" class="btn btn-primary dropdown-toggle"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        @Model
</button>
<button type="button" class="btn btn-primary dropdown-toggle"
        data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="caret"></span>
    <span class="sr-only">Toggle Dropdown</span>
</button>

DeaconCCGManagement/Views/Shared/_Layout.cshtml
@using DeaconCCGManagement.DAL
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Zion MBC Deacons CCG Management Portal</title>

    @*@Styles.Render("~/Content/styles")*@
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="~/css/font-awesome.min.css" rel="stylesheet" />
    <link href="~/Content/notify-metro.css" rel="stylesheet" />


    @Scripts.Render("~/bundles/modernizr")

    @RenderSection("styles", required: false)

</head>
<body id="page-top">

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                
                <span class="hidden-xs hidden-sm">
                    @Html.ActionLink("CCG Deacon Management Portal", "Index", "Home", null, new { @class = "navbar-brand" })
                </span>
                <span class="hidden-md hidden-lg hidden-xl">
                    @Html.ActionLink("CCG Management Portal", "Index", "Home", null, new { @class = "navbar-brand" })
                </span> 
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav top-nav-link">

                    <li>
                        <a href="@Url.Action("Index", "Home")">
                            <span class="glyphicon glyphicon-home"></span>&nbsp;Home
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("About", "Home")">
                            <span class="glyphicon glyphicon-info-sign"></span>&nbsp;About
                        </a>
                    </li>

                    <li>
                        <a href="@Url.Action("Contact", "Home")">
                            <span class="glyphicon glyphicon-envelope"></span>&nbsp;Contact
                        </a>
                    </li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>
                <span class="fa fa-copyright"></span> @DateTime.Now.Year - Zion MBC Deacons CCG Management Portal
            </p>
        </footer>
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/plugins")
    @Scripts.Render("~/Scripts/App/BreadcrumbTrail.js")

    <script src="~/Scripts/notify.js"></script>
    <script src="~/Scripts/jquery.signalR-2.3.0.min.js"></script>

    <script src="~/Scripts/notify-metro.js"></script>
    <script src="~/Scripts/App/NotifyJSService.js"></script>

    <!--Reference the auto-generated SignalR hub script. -->
    <script src="~/signalr/hubs"></script>   

    <script src="~/Scripts/App/SignalRNotifyService.js"></script>

    @RenderSection("scripts", required: false)
</body>
</html>

DeaconCCGManagement/Views/Shared/_MvcFileUploaderLayout_jui.cshtml
<!DOCTYPE html>
<html>
<head>
    <title>@ViewBag.Title</title>    
           
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/jquery-ui.min.js"></script>
    <!-- jQuery UI styles -->
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.10.3/themes/smoothness/jquery-ui.css" id="theme">

</head>
<body>
  <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          <a class="brand" href="#">Project name</a>
          <div class="nav-collapse collapse">
            <ul class="nav">
              <li class="active"><a href="#">Home</a></li>
              <li><a href="#about">About</a></li>
              <li><a href="#contact">Contact</a></li>
            </ul>
          </div><!--/.nav-collapse -->
        </div>
      </div>
    </div>

    <div class="container">
        <h3>Mvc File uploader Demo</h3>
        
        @RenderBody()

    </div> <!-- /container -->        

    @RenderSection("Scripts", false)
</body>
</html>

DeaconCCGManagement/Views/Shared/_NotificationBellPartial.cshtml
<a id="notify-link" href="#">
    <div class="notify-bell-base">
        <span id="notify-bell" class="glyphicon glyphicon-bell notify-inactive"></span>
        <span id="notify-count" class="badge notify-badge"></span>&nbsp;
    </div>
</a>

DeaconCCGManagement/Views/Shared/_SearchFieldAndButton.cshtml
@model DeaconCCGManagement.ViewModels.SearchViewModel

<!--Search field and button-->
<p>
    <div class="input-group pull-right">
        <input name="query" type="text" class="form-control"
               placeholder="@Model.Placeholder" style="float: right" value="@Model.Value">
        <span class="input-group-btn">
            <button class="btn btn-primary" type="submit">
                <i class="fa fa-search"></i>
            </button>
        </span>
    </div>
</p><!-- / Search field and button-->